/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MetricasRouteImport } from './routes/metricas'
import { Route as DisciplinasRouteImport } from './routes/disciplinas'
import { Route as CronogramaRouteImport } from './routes/cronograma'
import { Route as IndexRouteImport } from './routes/index'

const MetricasRoute = MetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplinasRoute = DisciplinasRouteImport.update({
  id: '/disciplinas',
  path: '/disciplinas',
  getParentRoute: () => rootRouteImport,
} as any)
const CronogramaRoute = CronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cronograma': typeof CronogramaRoute
  '/disciplinas': typeof DisciplinasRoute
  '/metricas': typeof MetricasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cronograma': typeof CronogramaRoute
  '/disciplinas': typeof DisciplinasRoute
  '/metricas': typeof MetricasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cronograma': typeof CronogramaRoute
  '/disciplinas': typeof DisciplinasRoute
  '/metricas': typeof MetricasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cronograma' | '/disciplinas' | '/metricas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cronograma' | '/disciplinas' | '/metricas'
  id: '__root__' | '/' | '/cronograma' | '/disciplinas' | '/metricas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CronogramaRoute: typeof CronogramaRoute
  DisciplinasRoute: typeof DisciplinasRoute
  MetricasRoute: typeof MetricasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/metricas': {
      id: '/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof MetricasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disciplinas': {
      id: '/disciplinas'
      path: '/disciplinas'
      fullPath: '/disciplinas'
      preLoaderRoute: typeof DisciplinasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronograma': {
      id: '/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof CronogramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CronogramaRoute: CronogramaRoute,
  DisciplinasRoute: DisciplinasRoute,
  MetricasRoute: MetricasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
