/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MetricasRouteImport } from './routes/metricas'
import { Route as DisciplinasRouteImport } from './routes/disciplinas'
import { Route as CronogramaRouteImport } from './routes/cronograma'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DisciplinasIdRouteImport } from './routes/disciplinas.$id'

const MetricasRoute = MetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplinasRoute = DisciplinasRouteImport.update({
  id: '/disciplinas',
  path: '/disciplinas',
  getParentRoute: () => rootRouteImport,
} as any)
const CronogramaRoute = CronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplinasIdRoute = DisciplinasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DisciplinasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cronograma': typeof CronogramaRoute
  '/disciplinas': typeof DisciplinasRouteWithChildren
  '/metricas': typeof MetricasRoute
  '/disciplinas/$id': typeof DisciplinasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cronograma': typeof CronogramaRoute
  '/disciplinas': typeof DisciplinasRouteWithChildren
  '/metricas': typeof MetricasRoute
  '/disciplinas/$id': typeof DisciplinasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cronograma': typeof CronogramaRoute
  '/disciplinas': typeof DisciplinasRouteWithChildren
  '/metricas': typeof MetricasRoute
  '/disciplinas/$id': typeof DisciplinasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cronograma'
    | '/disciplinas'
    | '/metricas'
    | '/disciplinas/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cronograma' | '/disciplinas' | '/metricas' | '/disciplinas/$id'
  id:
    | '__root__'
    | '/'
    | '/cronograma'
    | '/disciplinas'
    | '/metricas'
    | '/disciplinas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CronogramaRoute: typeof CronogramaRoute
  DisciplinasRoute: typeof DisciplinasRouteWithChildren
  MetricasRoute: typeof MetricasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/metricas': {
      id: '/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof MetricasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disciplinas': {
      id: '/disciplinas'
      path: '/disciplinas'
      fullPath: '/disciplinas'
      preLoaderRoute: typeof DisciplinasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronograma': {
      id: '/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof CronogramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disciplinas/$id': {
      id: '/disciplinas/$id'
      path: '/$id'
      fullPath: '/disciplinas/$id'
      preLoaderRoute: typeof DisciplinasIdRouteImport
      parentRoute: typeof DisciplinasRoute
    }
  }
}

interface DisciplinasRouteChildren {
  DisciplinasIdRoute: typeof DisciplinasIdRoute
}

const DisciplinasRouteChildren: DisciplinasRouteChildren = {
  DisciplinasIdRoute: DisciplinasIdRoute,
}

const DisciplinasRouteWithChildren = DisciplinasRoute._addFileChildren(
  DisciplinasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CronogramaRoute: CronogramaRoute,
  DisciplinasRoute: DisciplinasRouteWithChildren,
  MetricasRoute: MetricasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
